const datosONG = [
  {
    id: 1,
    name: "sociedad de bomberos voluntarios de hilario ascasubi",
    code: 8391,
    state: "buenos aires",
    cuit: "30-54304301-6",
    address: "calle 123, hilario ascasubi, buenos aires",
    email: "contacto@bomberosascasubi.org",
    web_site: "http://www.bomberosascasubi.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Ayuda a Víctimas de Inundaciones",
        description: "Ayuda a las víctimas de inundaciones en la región",
        image: "https://example.com/campaign1.jpg",
        startDate: "2023-10-01",
        endDate: "2023-11-30",
        finalAmount: 2500000,
        state: "active",
        category: "Trabajo",
      },
      {
        id: 2,
        name: "Campaña de Educación para Niños",
        description: "Brindar educación a niños desfavorecidos",
        image: "https://example.com/campaign2.jpg",
        startDate: "2023-09-15",
        endDate: "2023-12-15",
        finalAmount: 1500000,
        state: "active",
        category: "Educación",
      },
    ],
  },
  {
    id: 2,
    name: "merceditas",
    code: 8849,
    state: "chaco",
    cuit: "30-54304301-6",
    address: "calle 456, resistencia, chaco",
    email: "contacto@merceditas.org",
    web_site: "http://www.merceditas.org",
    state: true,
    campañas: [
      {
        id: 1,
        name: "Campaña de Alimentos para Niños",
        description: "Recaudación de alimentos para niños necesitados",
        image: "https://example.com/campaign3.jpg",
        startDate: "2023-10-10",
        endDate: "2023-11-30",
        finalAmount: 500000,
        state: "active",
        category: "Social",
      },
      {
        id: 2,
        name: "Campaña de Apoyo a Personas Mayores",
        description: "Brindar apoyo a personas mayores en situación de soledad",
        image: "https://example.com/campaign4.jpg",
        startDate: "2023-09-20",
        endDate: "2023-12-20",
        finalAmount: 800000,
        state: "active",
        category: "Salud",
      },
    ],
  },
  {
    id: 3,
    name: "club social y deportivo roca",
    code: 18735,
    state: "río negro",
    cuit: "30-54333752-4",
    address: "calle 789, general roca, río negro",
    email: "contacto@clubroca.org",
    web_site: "http://www.clubroca.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Deporte para Jóvenes",
        description:
          "Fomentar la participación de jóvenes en actividades deportivas",
        image: "https://example.com/campaign5.jpg",
        startDate: "2023-10-05",
        endDate: "2023-11-30",
        finalAmount: 1200000,
        state: "active",
        category: "Deportes / Recreación",
      },
    ],
  },
  {
    id: 4,
    name: "asociación civil sanjuanina de intercambio cultural y biblioteca popular americas",
    code: 33834,
    state: "san juan",
    cuit: "30-54338856-0",
    address: "calle 456, san juan, san juan",
    email: "contacto@bibliotecaamericas.org",
    web_site: "http://www.bibliotecaamericas.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Fomento a la Lectura",
        description: "Promover la lectura en la comunidad",
        image: "https://example.com/campaign6.jpg",
        startDate: "2023-10-15",
        endDate: "2023-12-15",
        finalAmount: 950000,
        state: "active",
        category: "Cultura",
      },
    ],
  },
  {
    id: 5,
    name: "fundación nuevo sol",
    code: 4447,
    state: "tucumán",
    cuit: "30-54351727-1",
    address: "calle 123, San Miguel de Tucumán, Tucumán",
    email: "contacto@fundacionnuevosol.org",
    web_site: "http://www.fundacionnuevosol.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Educación Ambiental",
        description: "Promover la conciencia ambiental en la comunidad",
        image: "https://example.com/campaign7.jpg",
        startDate: "2023-10-08",
        endDate: "2023-12-08",
        finalAmount: 1800000,
        state: "active",
        category: "Medio ambiente",
      },
    ],
  },
  {
    id: 6,
    name: "grupo de juventud solidaria del barrio dolores prats de huisi la estanzuela",
    code: 1684,
    state: "mendoza",
    cuit: "30-54392625-2",
    address: "calle 789, Mendoza, Mendoza",
    email: "contacto@juventudsolidaria.org",
    web_site: "http://www.juventudsolidaria.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Apoyo a la Juventud",
        description:
          "Brindar oportunidades a jóvenes en situación de vulnerabilidad",
        image: "https://example.com/campaign8.jpg",
        startDate: "2023-10-12",
        endDate: "2023-12-12",
        finalAmount: 1300000,
        state: "active",
        category: "Social",
      },
      {
        id: 2,
        name: "Campaña de Arte y Cultura",
        description: "Fomentar actividades culturales en la comunidad",
        image: "https://example.com/campaign9.jpg",
        startDate: "2023-09-25",
        endDate: "2023-11-30",
        finalAmount: 750000,
        state: "active",
        category: "Cultura",
      },
    ],
  },
  {
    id: 7,
    name: "centro vecinal barrio san carlos",
    code: 7667,
    state: "jujuy",
    cuit: "30-54392625-2",
    address: "calle 123, San Salvador de Jujuy, Jujuy",
    email: "contacto@centrosancarlos.org",
    web_site: "http://www.centrosancarlos.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Ayuda a Personas Mayores",
        description: "Brindar apoyo a personas mayores en situación de soledad",
        image: "https://example.com/campaign10.jpg",
        startDate: "2023-10-05",
        endDate: "2023-11-30",
        finalAmount: 900000,
        state: "active",
        category: "Salud",
      },
    ],
  },
  {
    id: 8,
    name: "fundación unidos por jujuy",
    code: 13253,
    state: "jujuy",
    cuit: "30-54400061-2",
    address: "calle 123, San Salvador de Jujuy, Jujuy",
    email: "contacto@fundacionunidos.org",
    web_site: "http://www.fundacionunidos.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Apoyo a Familias Vulnerables",
        description: "Brindar apoyo a familias en situación de vulnerabilidad",
        image: "https://example.com/campaign11.jpg",
        startDate: "2023-10-10",
        endDate: "2023-12-10",
        finalAmount: 2200000,
        state: "active",
        category: "Social",
      },
    ],
  },
  {
    id: 9,
    name: "asociación mutual círculo de suboficiales del ejército",
    code: 31902,
    state: "neuquén",
    cuit: "30-54406945-7",
    address: "calle 456, Neuquén, Neuquén",
    email: "contacto@circulosuboficiales.org",
    web_site: "http://www.circulosuboficiales.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Apoyo a Veteranos de Guerra",
        description: "Brindar apoyo a veteranos de guerra y sus familias",
        image: "https://example.com/campaign12.jpg",
        startDate: "2023-09-28",
        endDate: "2023-11-30",
        finalAmount: 1800000,
        state: "active",
        category: "Salud",
      },
      {
        id: 2,
        name: "Campaña de Educación para Niños",
        description: "Brindar educación a niños desfavorecidos",
        image: "https://example.com/campaign13.jpg",
        startDate: "2023-10-15",
        endDate: "2023-12-15",
        finalAmount: 1500000,
        state: "active",
        category: "Educación",
      },
    ],
  },
  {
    id: 10,
    name: "sporting club mutual social deportiva cultural y biblioteca",
    code: 30913,
    state: "córdoba",
    cuit: "30-54407123-4",
    address: "calle 123, Córdoba, Córdoba",
    email: "contacto@sportingclubcordoba.org",
    web_site: "http://www.sportingclubcordoba.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Deporte y Recreación",
        description:
          "Promover actividades deportivas y recreativas en la comunidad",
        image: "https://example.com/campaign14.jpg",
        startDate: "2023-10-05",
        endDate: "2023-11-30",
        finalAmount: 1300000,
        state: "active",
        category: "Deportes / Recreación",
      },
      {
        id: 2,
        name: "Campaña de Cultura y Arte",
        description:
          "Fomentar actividades culturales y artísticas en la comunidad",
        image: "https://example.com/campaign15.jpg",
        startDate: "2023-09-20",
        endDate: "2023-12-20",
        finalAmount: 800000,
        state: "active",
        category: "Cultura",
      },
    ],
  },
  {
    id: 11,
    name: "asociación mutual circulo de suboficiales del ejercito",
    code: 18742,
    state: "ciudad autónoma de buenos aires",
    cuit: "30-54409945-7",
    address: "calle 789, Ciudad Autónoma de Buenos Aires",
    email: "contacto@circulosuboficialescba.org",
    web_site: "http://www.circulosuboficialescba.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Apoyo a Veteranos de Guerra",
        description: "Brindar apoyo a veteranos de guerra y sus familias",
        image: "https://example.com/campaign16.jpg",
        startDate: "2023-10-28",
        endDate: "2023-12-31",
        finalAmount: 2800000,
        state: "active",
        category: "Salud",
      },
      {
        id: 2,
        name: "Campaña de Educación para Jóvenes",
        description: "Brindar educación a jóvenes desfavorecidos",
        image: "https://example.com/campaign17.jpg",
        startDate: "2023-09-15",
        endDate: "2023-12-15",
        finalAmount: 1500000,
        state: "active",
        category: "Educación",
      },
    ],
  },
  {
    id: 12,
    name: "fundación evita",
    code: 6766,
    state: "tucumán",
    cuit: "30-54420964-3",
    address: "calle 456, San Miguel de Tucumán, Tucumán",
    email: "contacto@fundacionevita.org",
    web_site: "http://www.fundacionevita.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Alimentos para Niños",
        description: "Recaudación de alimentos para niños necesitados",
        image: "https://example.com/campaign18.jpg",
        startDate: "2023-10-10",
        endDate: "2023-11-30",
        finalAmount: 500000,
        state: "active",
        category: "Social",
      },
      {
        id: 2,
        name: "Campaña de Apoyo a Personas Mayores",
        description: "Brindar apoyo a personas mayores en situación de soledad",
        image: "https://example.com/campaign19.jpg",
        startDate: "2023-09-20",
        endDate: "2023-12-20",
        finalAmount: 800000,
        state: "active",
        category: "Salud",
      },
    ],
  },
  {
    id: 13,
    name: "centro solidario union y patria",
    code: 1680,
    state: "mendoza",
    cuit: "30-54440027-0",
    address: "calle 123, Mendoza, Mendoza",
    email: "contacto@unionypatria.org",
    web_site: "http://www.unionypatria.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Alimentos para Familias Necesitadas",
        description:
          "Recaudación de alimentos para familias en situación de vulnerabilidad",
        image: "https://example.com/campaign20.jpg",
        startDate: "2023-10-18",
        endDate: "2023-11-30",
        finalAmount: 1200000,
        state: "active",
        category: "Social",
      },
    ],
  },
  {
    id: 14,
    name: "centro social y cultural vecinos de almagro y caballito",
    code: 6286,
    state: "ciudad autónoma de buenos aires",
    cuit: "30-54454045-9",
    address: "calle 456, Buenos Aires, Ciudad Autónoma de Buenos Aires",
    email: "contacto@vecinosalmagroycaballito.org",
    web_site: "http://www.vecinosalmagroycaballito.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Arte y Cultura",
        description:
          "Fomentar actividades culturales y artísticas en la comunidad",
        image: "https://example.com/campaign21.jpg",
        startDate: "2023-10-15",
        endDate: "2023-12-15",
        finalAmount: 800000,
        state: "active",
        category: "Cultura",
      },
    ],
  },
  {
    id: 15,
    name: "servicio de orientación familiar villa esperanza",
    code: 13009,
    state: "buenos aires",
    cuit: "30-54475480-7",
    address: "calle 123, Villa Esperanza, Buenos Aires",
    email: "contacto@villaesperanza.org",
    web_site: "http://www.villaesperanza.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Apoyo a Familias Vulnerables",
        description: "Brindar apoyo a familias en situación de vulnerabilidad",
        image: "https://example.com/campaign22.jpg",
        startDate: "2023-10-10",
        endDate: "2023-11-30",
        finalAmount: 1200000,
        state: "active",
        category: "Social",
      },
      {
        id: 2,
        name: "Campaña de Educación para Niños",
        description: "Brindar educación a niños desfavorecidos",
        image: "https://example.com/campaign23.jpg",
        startDate: "2023-09-25",
        endDate: "2023-12-31",
        finalAmount: 1500000,
        state: "active",
        category: "Educación",
      },
    ],
  },
  {
    id: 16,
    name: "manos a la obra",
    code: 13710,
    state: "misiones",
    cuit: "30-54477137-6",
    address: "calle 456, Posadas, Misiones",
    email: "contacto@manosaobra.org",
    web_site: "http://www.manosaobra.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Construcción de Viviendas",
        description:
          "Construir viviendas para familias en situación de necesidad",
        image: "https://example.com/campaign24.jpg",
        startDate: "2023-10-20",
        endDate: "2023-12-20",
        finalAmount: 2500000,
        state: "active",
        category: "Vivienda",
      },
    ],
  },
  {
    id: 17,
    name: "asociacion mutual casa del boxeador",
    code: 18807,
    state: "ciudad autónoma de buenos aires",
    cuit: "30-54496846-3",
    address: "calle 789, Ciudad Autónoma de Buenos Aires",
    email: "contacto@casadelboxeador.org",
    web_site: "http://www.casadelboxeador.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Apoyo a Jóvenes Deportistas",
        description: "Brindar apoyo a jóvenes deportistas en su formación",
        image: "https://example.com/campaign25.jpg",
        startDate: "2023-10-25",
        endDate: "2023-12-25",
        finalAmount: 1800000,
        state: "active",
        category: "Deportes / Recreación",
      },
    ],
  },
  {
    id: 18,
    name: "cuerpo de bomberos voluntarios de villa maría",
    code: 18732,
    state: "córdoba",
    cuit: "30-54500747-5",
    address: "calle 123, Villa María, Córdoba",
    email: "contacto@bomberosvillamaria.org",
    web_site: "http://www.bomberosvillamaria.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Equipamiento para Bomberos",
        description:
          "Adquirir equipos y herramientas para el cuerpo de bomberos",
        image: "https://example.com/campaign26.jpg",
        startDate: "2023-11-05",
        endDate: "2023-12-31",
        finalAmount: 3500000,
        state: "active",
        category: "Infraestructura, obras, servicios públicos",
      },
    ],
  },
  {
    id: 19,
    name: "centro de profesores de folklore del chaco",
    code: 990,
    state: "chaco",
    cuit: "30-54542280-4",
    address: "calle 456, Resistencia, Chaco",
    email: "contacto@profesoresdefolklorechaco.org",
    web_site: "http://www.profesoresdefolklorechaco.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Promoción de la Cultura Local",
        description: "Promover y preservar la cultura folklórica de la región",
        image: "https://example.com/campaign27.jpg",
        startDate: "2023-10-15",
        endDate: "2023-12-15",
        finalAmount: 900000,
        state: "active",
        category: "Cultura",
      },
    ],
  },
  {
    id: 20,
    name: "asociación de ayuda a niños con mielomeningocele hidrocefalia y otros-sgo. del estero",
    code: 5271,
    state: "santiago del estero",
    cuit: "30-54551592-6",
    address: "Calle 123, Santiago del Estero, Santiago del Estero",
    email: "contacto@ayudaaninosse.org",
    web_site: "http://www.ayudaaninosse.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Apoyo a Niños con Mielomeningocele",
        description:
          "Brindar apoyo médico y terapéutico a niños con mielomeningocele",
        image: "https://example.com/campaign28.jpg",
        startDate: "2023-11-01",
        endDate: "2023-12-31",
        finalAmount: 1100000,
        state: "active",
        category: "Salud",
      },
    ],
  },
  {
    id: 21,
    name: "dios dejano crecer",
    code: 9776,
    state: "santa fe",
    cuit: "30-54551592-6",
    address: "Calle 456, Santa Fe, Santa Fe",
    email: "contacto@dejanocrecer.org",
    web_site: "http://www.dejanocrecer.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Educación para Jóvenes",
        description:
          "Brindar educación y oportunidades a jóvenes en riesgo social",
        image: "https://example.com/campaign29.jpg",
        startDate: "2023-11-10",
        endDate: "2023-12-31",
        finalAmount: 950000,
        state: "active",
        category: "Educación",
      },
    ],
  },
  {
    id: 22,
    name: "fundacion fains",
    code: 9991,
    state: "tucumán",
    cuit: "30-54563797-5",
    address: "Calle 123, San Miguel de Tucumán, Tucumán",
    email: "contacto@fundacionfains.org",
    web_site: "http://www.fundacionfains.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Desarrollo Comunitario",
        description: "Promover el desarrollo sostenible en comunidades locales",
        image: "https://example.com/campaign30.jpg",
        startDate: "2023-11-05",
        endDate: "2023-12-31",
        finalAmount: 3800000,
        state: "active",
        category: "Economía",
      },
    ],
  },
  {
    id: 23,
    name: "cooperativa batan de obras y servicios publicos ltada",
    code: 5015,
    state: "buenos aires",
    cuit: "30-54566680-0",
    address: "Calle 456, Batán, Buenos Aires",
    email: "contacto@cooperativabatan.org",
    web_site: "http://www.cooperativabatan.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Mejora de Infraestructura",
        description: "Realizar mejoras en la infraestructura de la comunidad",
        image: "https://example.com/campaign31.jpg",
        startDate: "2023-11-08",
        endDate: "2023-12-31",
        finalAmount: 2600000,
        state: "active",
        category: "Infraestructura, obras, servicios públicos",
      },
    ],
  },
  {
    id: 24,
    name: "consejo provincial de ongs jujuy",
    code: 9977,
    state: "jujuy",
    cuit: "30-54569269-0",
    address: "Calle 123, San Salvador de Jujuy, Jujuy",
    email: "contacto@consejoongsjujuy.org",
    web_site: "http://www.consejoongsjujuy.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Capacitación para ONGs",
        description: "Brindar capacitación a organizaciones no gubernamentales",
        image: "https://example.com/campaign32.jpg",
        startDate: "2023-11-15",
        endDate: "2023-12-31",
        finalAmount: 1800000,
        state: "active",
        category: "Educación",
      },
    ],
  },
  {
    id: 25,
    name: "caminos abiertos",
    code: 12300,
    state: "ciudad autónoma de buenos aires",
    cuit: "30-54571617-4",
    address: "Calle 789, Ciudad Autónoma de Buenos Aires",
    email: "contacto@caminosabiertos.org",
    web_site: "http://www.caminosabiertos.org",
    state: false,
    campañas: [
      {
        id: 1,
        name: "Campaña de Apoyo a Personas sin Hogar",
        description: "Brindar apoyo a personas en situación de calle",
        image: "https://example.com/campaign33.jpg",
        startDate: "2023-11-20",
        endDate: "2023-12-31",
        finalAmount: 750000,
        state: "active",
        category: "Social",
      },
    ],
  },
];

export default datosONG;

/////////////////////////////////////////////////////////////////////////////////

/*
//Por si se los necesita hay 50 registros de ONGs sin las campañas ni categorías.
[
  {
    id: 1,
    name: "Sociedad de Bomberos Voluntarios de Hilario Ascasubi",
    code: 8391,
    state: "Buenos Aires",
    cuit: "30-54304301-6",
    address: "Calle 123, Hilario Ascasubi, Buenos Aires",
    email: "info@bomberosascasubi.org",
    web_site: "http://www.bomberosascasubi.org",
    state: false,
  },
  {
    id: 2,
    name: "Merceditas",
    code: 8849,
    state: "Chaco",
    cuit: "30-54304301-6",
    address: "Avenida 456, Resistencia, Chaco",
    email: "contacto@merceditas.org",
    web_site: "http://www.merceditas.org",
    state: true,
  },
  {
    id: 3,
    name: "Club Social y Deportivo Roca",
    code: 18735,
    state: "Río Negro",
    cuit: "30-54333752-4",
    address: "Calle 789, General Roca, Río Negro",
    email: "clubroca@clubroca.org",
    web_site: "http://www.clubroca.org",
    state: false,
  },
  {
    id: 4,
    name: "Asociación Civil Sanjuanina de Intercambio Cultural y Biblioteca Popular Americas",
    code: 33834,
    state: "San Juan",
    cuit: "30-54338856-0",
    address: "Avenida Libertador 567, San Juan",
    email: "contacto@americas.org",
    web_site: "http://www.americas.org",
    state: false,
  },
  {
    id: 5,
    name: "Fundación Nuevo Sol",
    code: 4447,
    state: "Tucumán",
    cuit: "30-54351727-1",
    address: "Calle 456, San Miguel de Tucumán, Tucumán",
    email: "info@fundacionnuevosol.org",
    web_site: "http://www.fundacionnuevosol.org",
    state: false,
  },
  {
    id: 6,
    name: "Grupo de Juventud Solidaria Del Barrio Dolores Prats de Huisi la Estanzuela",
    code: 1684,
    state: "Mendoza",
    cuit: "30-54392625-2",
    address: "Calle 789, Mendoza, Mendoza",
    email: "contacto@juventudsolidaria.org",
    web_site: "http://www.juventudsolidaria.org",
    state: false,
  },
  {
    id: 7,
    name: "Centro Vecinal Barrio San Carlos",
    code: 7667,
    state: "Jujuy",
    cuit: "30-54392625-2",
    address: "Calle 123, San Carlos, Jujuy",
    email: "info@barriosancarlos.org",
    web_site: "http://www.barriosancarlos.org",
    state: false,
  },
  {
    id: 8,
    name: "Fundación Unidos por Jujuy",
    code: 13253,
    state: "Jujuy",
    cuit: "30-54400061-2",
    address: "Avenida 456, San Salvador de Jujuy, Jujuy",
    email: "info@unidosporjujuy.org",
    web_site: "http://www.unidosporjujuy.org",
    state: true,
  },
  {
    id: 9,
    name: "Asociación Mutual Circulo de Suboficiales del Ejercito",
    code: 31902,
    state: "Neuquén",
    cuit: "30-54406945-7",
    address: "Calle 789, Neuquén, Neuquén",
    email: "contacto@circulosuboficiales.org",
    web_site: "http://www.circulosuboficiales.org",
    state: true,
  },
  {
    id: 10,
    name: "Sporting Club Mutual Social Deportiva Cultural y Biblioteca",
    code: 30913,
    state: "Córdoba",
    cuit: "30-54407123-4",
    address: "Avenida 123, Córdoba, Córdoba",
    email: "info@sportingclub.org",
    web_site: "http://www.sportingclub.org",
    state: false,
  },
  {
    id: 11,
    name: "Fundación Evita",
    code: 6766,
    state: "Tucumán",
    cuit: "30-54420964-3",
    address: "Calle 567, San Miguel de Tucumán, Tucumán",
    email: "contacto@fundacionevita.org",
    web_site: "http://www.fundacionevita.org",
    state: true,
  },
  {
    id: 12,
    name: "Centro Solidario Union y Patria",
    code: 1680,
    state: "Mendoza",
    cuit: "30-54440027-0",
    address: "Avenida 123, Mendoza, Mendoza",
    email: "info@unionypatria.org",
    web_site: "http://www.unionypatria.org",
    state: false,
  },
  {
    id: 13,
    name: "Centro Social y Cultural Vecinos de Almagro y Caballito",
    code: 6286,
    state: "Ciudad Autónoma de Buenos Aires",
    cuit: "30-54454045-9",
    address: "Calle 456, Buenos Aires, CABA",
    email: "info@vecinosalmagroycaballito.org",
    web_site: "http://www.vecinosalmagroycaballito.org",
    state: true,
  },
  {
    id: 14,
    name: "Servicio de Orientación Familiar Villa Esperanza",
    code: 13009,
    state: "Buenos Aires",
    cuit: "30-54475480-7",
    address: "Calle 789, Villa Esperanza, Buenos Aires",
    email: "contacto@villaesperanza.org",
    web_site: "http://www.villaesperanza.org",
    state: false,
  },
  {
    id: 15,
    name: "Manos a la obra",
    code: 13710,
    state: "Misiones",
    cuit: "30-54477137-6",
    address: "Avenida 123, Posadas, Misiones",
    email: "info@manosalaobra.org",
    web_site: "http://www.manosalaobra.org",
    state: true,
  },
  {
    id: 16,
    name: "Asociacion Mutual Casa del Boxeador",
    code: 18807,
    state: "Ciudad Autónoma de Buenos Aires",
    cuit: "30-54496846-3",
    address: "Calle 456, Buenos Aires, CABA",
    email: "contacto@casadelboxeador.org",
    web_site: "http://www.casadelboxeador.org",
    state: false,
  },
  {
    id: 17,
    name: "Cuerpo de bomberos voluntarios de Villa María",
    code: 18732,
    state: "Córdoba",
    cuit: "30-54500747-5",
    address: "Calle 789, Villa María, Córdoba",
    email: "info@bomberosvillamaria.org",
    web_site: "http://www.bomberosvillamaria.org",
    state: true,
  },
  {
    id: 18,
    name: "Centro de Profesores de Folklore Del Chaco",
    code: 990,
    state: "Chaco",
    cuit: "30-54542280-4",
    address: "Calle 123, Resistencia, Chaco",
    email: "contacto@folklorechaco.org",
    web_site: "http://www.folklorechaco.org",
    state: false,
  },
  {
    id: 19,
    name: "Asociación de Ayuda a Niños con Mielomenincocele Hidrocefalia y Otros-sgo. Del Estero",
    code: 5271,
    state: "Santiago del Estero",
    cuit: "30-54551592-6",
    address: "Avenida 456, Santiago del Estero, Santiago del Estero",
    email: "info@ayudaaninos.org",
    web_site: "http://www.ayudaaninos.org",
    state: true,
  },
  {
    id: 20,
    name: "Dios Dejano Crecer",
    code: 9776,
    state: "Santa Fe",
    cuit: "30-54551592-6",
    address: "Calle 789, Rosario, Santa Fe",
    email: "contacto@diosdejanocrecer.org",
    web_site: "http://www.diosdejanocrecer.org",
    state: false,
  },
  {
    id: 21,
    name: "Fundacion Fains",
    code: 9991,
    state: "Tucumán",
    cuit: "30-54563797-5",
    address: "Avenida 123, San Miguel de Tucumán, Tucumán",
    email: "info@fundacionfains.org",
    web_site: "http://www.fundacionfains.org",
    state: true,
  },
  {
    id: 22,
    name: "Cooperativa Batan de Obras y Servicios Publicos Ltada",
    code: 5015,
    state: "Buenos Aires",
    cuit: "30-54566680-0",
    address: "Calle 456, Mar del Plata, Buenos Aires",
    email: "contacto@cooperativabatan.org",
    web_site: "http://www.cooperativabatan.org",
    state: false,
  },
  {
    id: 23,
    name: "Consejo Provincial de Ongs Jujuy",
    code: 9977,
    state: "Jujuy",
    cuit: "30-54569269-0",
    address: "Avenida 123, San Salvador de Jujuy, Jujuy",
    email: "info@consejoongsjujuy.org",
    web_site: "http://www.consejoongsjujuy.org",
    state: true,
  },
  {
    id: 24,
    name: "Caminos Abiertos",
    code: 12300,
    state: "Ciudad Autónoma de Buenos Aires",
    cuit: "30-54571617-4",
    address: "Calle 456, Buenos Aires, CABA",
    email: "contacto@caminosabiertos.org",
    web_site: "http://www.caminosabiertos.org",
    state: false,
  },
  {
    id: 25,
    name: "Fundacion Accion Oncohematologica",
    code: 9648,
    state: "Ciudad Autónoma de Buenos Aires",
    cuit: "30-54574623-5",
    address: "Calle 123, Buenos Aires, CABA",
    email: "info@acciononcohematologica.org",
    web_site: "http://www.acciononcohematologica.org",
    state: true,
  },
  {
    id: 26,
    name: "Fundación para la Capacitación ,el Desarrollo ,el Medio Ambiente y la Biodiversidad",
    code: 11062,
    state: "Salta",
    cuit: "30-54581014-6",
    address: "Avenida 456, Salta, Salta",
    email: "contacto@fundacionmedioambiente.org",
    web_site: "http://www.fundacionmedioambiente.org",
    state: false,
  },
  {
    id: 27,
    name: "Cooperadora Del Hospital Regional Benigno Carro",
    code: 7626,
    state: "Santa Cruz",
    cuit: "30-54583959-4",
    address: "Calle 789, Río Gallegos, Santa Cruz",
    email: "info@cooperadorabenignocarro.org",
    web_site: "http://www.cooperadorabenignocarro.org",
    state: true,
  },
  {
    id: 28,
    name: "2 de Abril",
    code: 8848,
    state: "Chaco",
    cuit: "30-54584303-6",
    address: "Calle 123, Resistencia, Chaco",
    email: "contacto@2deabril.org",
    web_site: "http://www.2deabril.org",
    state: false,
  },
  {
    id: 29,
    name: "Centro de Especialización y Aplicación del Trabajo Social",
    code: 13492,
    state: "Misiones",
    cuit: "30-54584853-4",
    address: "Calle 456, Posadas, Misiones",
    email: "info@ceats.org",
    web_site: "http://www.ceats.org",
    state: true,
  },
  {
    id: 30,
    name: "Sociedad de Beneficiencia de Pigue 'Hogar Federico Ducos'",
    code: 18747,
    state: "Buenos Aires",
    cuit: "30-54585801-7",
    address: "Calle 456, Pigüé, Buenos Aires",
    email: "contacto@hogarfededicoducos.org",
    web_site: "http://www.hogarfededicoducos.org",
    state: true,
  },
  {
    id: 31,
    name: "Asociación Argentina de Lucha Contra las Pseudociencias",
    code: 10078,
    state: "Buenos Aires",
    cuit: "30-54586774-1",
    address: "Calle 789, La Plata, Buenos Aires",
    email: "contacto@pseudociencias.org",
    web_site: "http://www.pseudociencias.org",
    state: true,
  },
  {
    id: 32,
    name: "Asociación las Golondrinas",
    code: 7327,
    state: "Buenos Aires",
    cuit: "30-54587463-2",
    address: "Calle 456, Bahía Blanca, Buenos Aires",
    email: "contacto@golondrinas.org",
    web_site: "http://www.golondrinas.org",
    state: false,
  },
  {
    id: 33,
    name: "Asociación Atlética Santa Ana",
    code: 12399,
    state: "Misiones",
    cuit: "30-54587609-0",
    address: "Calle 123, Santa Ana, Misiones",
    email: "info@santaana.org",
    web_site: "http://www.santaana.org",
    state: true,
  },
  {
    id: 34,
    name: "Asociación Judicial Bonaerense",
    code: 5192,
    state: "Buenos Aires",
    cuit: "30-54590814-6",
    address: "Calle 789, La Plata, Buenos Aires",
    email: "contacto@ajb.org",
    web_site: "http://www.ajb.org",
    state: false,
  },
  {
    id: 35,
    name: "Sociedad de beneficencia de Tucuman",
    code: 18771,
    state: "Tucumán",
    cuit: "30-54590821-9",
    address: "Avenida 456, San Miguel de Tucumán, Tucumán",
    email: "info@beneficenciatucuman.org",
    web_site: "http://www.beneficenciatucuman.org",
    state: true,
  },
  {
    id: 36,
    name: "Unión Vecinal Virgen de Andacollo la Laguna",
    code: 7072,
    state: "La Rioja",
    cuit: "30-54591305-0",
    address: "Calle 123, La Laguna, La Rioja",
    email: "contacto@virgendelalaguna.org",
    web_site: "http://www.virgendelalaguna.org",
    state: false,
  },
  {
    id: 37,
    name: "Asociación En Defensa Del Vecino, Del Usuario y Del Consumidor",
    code: 5882,
    state: "Salta",
    cuit: "30-54592797-3",
    address: "Calle 456, Salta, Salta",
    email: "contacto@defensadelvecino.org",
    web_site: "http://www.defensadelvecino.org",
    state: true,
  },
  {
    id: 38,
    name: "Escuela de Educación Media Nº",
    code: 7903,
    state: "Buenos Aires",
    cuit: "30-54593356-6",
    address: "Calle 789, La Plata, Buenos Aires",
    email: "info@escuelamedia.org",
    web_site: "http://www.escuelamedia.org",
    state: false,
  },
  {
    id: 39,
    name: "Asociacion Mutualista de Empleados del Banco de la Provincia de Buenos Aires",
    code: 18912,
    state: "Ciudad Autónoma de Buenos Aires",
    cuit: "30-54595994-8",
    address: "Calle 456, Buenos Aires, CABA",
    email: "contacto@mutualbankprovincia.org",
    web_site: "http://www.mutualbankprovincia.org",
    state: true,
  },
  {
    id: 40,
    name: "Asociación Civil Colegio José de San Martín",
    code: 10892,
    state: "Buenos Aires",
    cuit: "30-54596102-0",
    address: "Calle 123, San Martín, Buenos Aires",
    email: "info@colegiosanmartin.org",
    web_site: "http://www.colegiosanmartin.org",
    state: false,
  },
  {
    id: 41,
    name: "Sociedad Española de Socorros Mutuos",
    code: 18869,
    state: "Buenos Aires",
    cuit: "30-54599002-0",
    address: "Calle 456, Buenos Aires, CABA",
    email: "info@sociedadespanola.org",
    web_site: "http://www.sociedadespanola.org",
    state: true,
  },
  {
    id: 42,
    name: "Biblioteca Popular Eva Perón",
    code: 10909,
    state: "Corrientes",
    cuit: "30-54602290-7",
    address: "Calle 789, Corrientes, Corrientes",
    email: "contacto@bibliotecaevaperon.org",
    web_site: "http://www.bibliotecaevaperon.org",
    state: false,
  },
  {
    id: 43,
    name: "Par Activo",
    code: 3069,
    state: "Santa Fe",
    cuit: "30-54603392-5",
    address: "Calle 123, Rosario, Santa Fe",
    email: "info@paractivo.org",
    web_site: "http://www.paractivo.org",
    state: true,
  },
  {
    id: 44,
    name: "Radio Comunitaria Keops",
    code: 4396,
    state: "Buenos Aires",
    cuit: "30-54603392-5",
    address: "Calle 456, La Plata, Buenos Aires",
    email: "contacto@keopsradio.org",
    web_site: "http://www.keopsradio.org",
    state: false,
  },
  {
    id: 45,
    name: "Centro de Capacitacion y Formacion Profesional Laim Asociación Civil S/fines de Lucro",
    code: 5834,
    state: "Buenos Aires",
    cuit: "30-54603392-5",
    address: "Calle 123, Avellaneda, Buenos Aires",
    email: "info@laimformacion.org",
    web_site: "http://www.laimformacion.org",
    state: true,
  },
  {
    id: 46,
    name: "Institución Salesiana",
    code: 7026,
    state: "Santa Fe",
    cuit: "30-54603392-5",
    address: "Calle 456, Rosario, Santa Fe",
    email: "contacto@salesianos.org",
    web_site: "http://www.salesianos.org",
    state: false,
  },
  {
    id: 47,
    name: "Equipos de Acciones Sociales",
    code: 10458,
    state: "Ciudad Autónoma de Buenos Aires",
    cuit: "30-54603392-5",
    address: "Calle 123, Buenos Aires, CABA",
    email: "info@equiposaccionsociales.org",
    web_site: "http://www.equiposaccionsociales.org",
    state: true,
  },
  {
    id: 48,
    name: "Comisión de Fomento para el Desarrollo Social Cultural y Económico la Consulta",
    code: 10711,
    state: "Mendoza",
    cuit: "30-54603392-5",
    address: "Calle 789, La Consulta, Mendoza",
    email: "contacto@fomentolaconsulta.org",
    web_site: "http://www.fomentolaconsulta.org",
    state: false,
  },
  {
    id: 49,
    name: "CRUZ ROJA ARGENTINA FILIAL SALTA",
    code: 27699,
    state: "Salta",
    cuit: "30-54603392-5",
    address: "Calle 456, Salta, Salta",
    email: "contacto@cruzrojasalta.org",
    web_site: "http://www.cruzrojasalta.org",
    state: true,
  },
  {
    id: 50,
    name: "Iglesia Cristiana Casa de Misericordia",
    code: 1853,
    state: "Chaco",
    cuit: "30-54608687-5",
    address: "Calle 123, Resistencia, Chaco",
    email: "contacto@casademisericordia.org",
    web_site: "http://www.casademisericordia.org",
    state: false,
  },
];
*/
////////////////////////////////////////////////////////////////////////////////////////
