/*
// Ver de agregar las campañas
[  
  {
    id: 1,
    nombreDonante: "Juan Pérez",
    email: "juanperez@example.com",
    amountDonated: 25000.0,
  },
  {
    id: 2,
    nombreDonante: "María Rodríguez",
    email: "mariarodriguez@example.com",
    amountDonated: 150000.0,
  },
  {
    id: 3,
    nombreDonante: "Carlos Gómez",
    email: "carlosgomez@example.com",
    amountDonated: 75000.0,
  },
  {
    id: 4,
    nombreDonante: "Laura Martínez",
    email: "lauramartinez@example.com",
    amountDonated: 300000.0,
  },
  {
    id: 5,
    nombreDonante: "Luis Fernández",
    email: "luisfernandez@example.com",
    amountDonated: 20000.0,
  },
  {
    id: 6,
    nombreDonante: "Ana López",
    email: "analopez@example.com",
    amountDonated: 450000.0,
  },
  {
    id: 7,
    nombreDonante: "Pedro González",
    email: "pedrogonzalez@example.com",
    amountDonated: 60000.0,
  },
  {
    id: 8,
    nombreDonante: "Carmen Díaz",
    email: "carmendiaz@example.com",
    amountDonated: 75000.0,
  },
  {
    id: 9,
    nombreDonante: "Diego Pérez",
    email: "diegoperez@example.com",
    amountDonated: 100000.0,
  },
  {
    id: 10,
    nombreDonante: "Isabel Rodríguez",
    email: "isabelrodriguez@example.com",
    amountDonated: 450000.0,
  },
  {
    id: 11,
    nombreDonante: "Jorge Sánchez",
    email: "jorgesanchez@example.com",
    amountDonated: 30000.0,
  },
  {
    id: 12,
    nombreDonante: "Elena Pérez",
    email: "elenaperez@example.com",
    amountDonated: 200000.0,
  },
  {
    id: 13,
    nombreDonante: "Miguel Rodríguez",
    email: "miguelrodriguez@example.com",
    amountDonated: 180000.0,
  },
  {
    id: 14,
    nombreDonante: "Patricia López",
    email: "patricialopez@example.com",
    amountDonated: 40000.0,
  },
  {
    id: 15,
    nombreDonante: "Ricardo González",
    email: "ricardogonzalez@example.com",
    amountDonated: 220000.0,
  },
  {
    id: 16,
    nombreDonante: "Sofía Díaz",
    email: "sofiadiaz@example.com",
    amountDonated: 280000.0,
  },
  {
    id: 17,
    nombreDonante: "Javier Martínez",
    email: "javiermartinez@example.com",
    amountDonated: 75000.0,
  },
  {
    id: 18,
    nombreDonante: "Lucía Fernández",
    email: "luciafernandez@example.com",
    amountDonated: 350000.0,
  },
  {
    id: 19,
    nombreDonante: "Alejandro López",
    email: "alejandrolopez@example.com",
    amountDonated: 120000.0,
  },
  {
    id: 20,
    nombreDonante: "Cecilia González",
    email: "ceciliagonzalez@example.com",
    amountDonated: 22000.0,
  },
  {
    id: 21,
    nombreDonante: "Raúl Pérez",
    email: "raulperez@example.com",
    amountDonated: 28000.0,
  },
  {
    id: 22,
    nombreDonante: "Carolina Rodríguez",
    email: "carolinarodriguez@example.com",
    amountDonated: 75000.0,
  },
  {
    id: 23,
    nombreDonante: "Andrés Díaz",
    email: "andresdiaz@example.com",
    amountDonated: 200000.0,
  },
  {
    id: 24,
    nombreDonante: "Marcela López",
    email: "marcelalopez@example.com",
    amountDonated: 300000.0,
  },
  {
    id: 25,
    nombreDonante: "Gustavo González",
    email: "gustavogonzalez@example.com",
    amountDonated: 150000.0,
  },
  {
    id: 26,
    nombreDonante: "Liliana Pérez",
    email: "lilianaperez@example.com",
    amountDonated: 180000.0,
  },
  {
    id: 27,
    nombreDonante: "Roberto Rodríguez",
    email: "robertorodriguez@example.com",
    amountDonated: 450000.0,
  },
  {
    id: 28,
    nombreDonante: "Adriana González",
    email: "adrianagonzalez@example.com",
    amountDonated: 75000.0,
  },
  {
    id: 29,
    nombreDonante: "Fernando Díaz",
    email: "fernandodiaz@example.com",
    amountDonated: 120000.0,
  },
  {
    id: 30,
    nombreDonante: "Valeria López",
    email: "valerialopez@example.com",
    amountDonated: 280000.0,
  },
  {
    id: 31,
    nombreDonante: "Mariano Pérez",
    email: "marianoperez@example.com",
    amountDonated: 10000.0,
  },
];
*/
